# 配置数据库信息
spring:
  datasource:
    url: jdbc://mysql://10.188.36.4:8101/sf01399094_wnp
    username: sf01399094
    password: 1q2w3e@sf


person:
  name: A
  age: 13
  happy: false
  birth: 2020/09/09
  maps: {K1: v1, k2: v2}
  lists: 
    - code
    - music
    - girl
dog:
  name: 小狗狗
  age: 1
email:
  eName: email
  eAge: 27
  eValue: test@qq.com
  
